#!/usr/bin/env bash

set -xe

echo "############### Testing:"
#echo PG_PROBACKUP_PARANOIA=${PG_PROBACKUP_PARANOIA}
#echo ARCHIVE_COMPRESSION=${ARCHIVE_COMPRESSION}
#echo PGPROBACKUPBIN_OLD=${PGPROBACKUPBIN_OLD}
#echo PGPROBACKUPBIN=${PGPROBACKUPBIN}
#echo PGPROBACKUP_SSH_REMOTE=${PGPROBACKUP_SSH_REMOTE}
#echo PGPROBACKUP_GDB=${PGPROBACKUP_GDB}
#echo PG_PROBACKUP_PTRACK=${PG_PROBACKUP_PTRACK}

export PG_BIN_DIR=${PWD}/pg/${PG_VERSION}
export PG_CONFIG=${PG_BIN_DIR}/bin/pg_config
export PG_PROBACKUP_TEST_BASIC=ON
python3 -m unittest -v tests'
